js:

  dmOppPlugin:

    map:                  map
    admin:                admin

css:

  dmOppPlugin:

    admin:                admin
    print:                print
    blueprint:            blueprint/screen