<?php

/**
 * PluginElementCategTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginElementCategTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginElementCategTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginElementCateg');
    }
}