<?php

/**
 * PluginPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class PluginPhoto extends BasePhoto
{

  public function getCoords()
  {
    return array($this->latitude, $this->longitude);
  }

  public function getBestDate()
  {
    return $this->date ? $this->date : $this->annee;
  }

  public function __toString()
  {
    return $this->get('nom') ? $this->get('nom') : 'Photo '.$this->get('id');
  }
  
  public function preSave($event)
  {
    parent::preSave($event);

    if($user = $this->getService('user'))
    {
      if(!$this->createdBy)
      {
        $this->createdBy = $user->getUserId();
      }

      $this->updatedBy = $user->getUserId();
    }
  }
}