<?php

/**
 * PluginElementCategElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginElementCategElementTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginElementCategElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginElementCategElement');
    }
}