generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: ElementCateg
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: element_categ
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        elements_list:
          label: Eléments
      list:
        display:
          - '=nom'
          - elements_list
          - created_at
          - updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - nom
          - created_at
          - updated_at
      form:
        display:
          NONE: [nom]
          Eléments: [elements_list]
        class: ElementCategAdminForm
        fields: {  }
      edit: ~
      new: ~
